name: Tests for the project on Linux

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  tests:
    name: Running the project tests on Linux 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Clone Zork++
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'ZeroDayCode'
          repository: 'Zork'

      - name: Download the latest working version of Clang
        run: |
          # Exit on error
          set -e
          # Download and execute the LLVM installation script for the specified Clang version
          echo "-----> Downloading and executing the LLVM installation script for Clang 16"
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16

          echo "-----> Installing libc++"
          sudo apt-get install -y libc++-16-dev libc++abi-16-dev libunwind-16 libunwind-16-dev libc6 libzstd1

          # Update the symbolic link to point to the newly installed Clang version
          echo "-----> Updating the symbolic link to point to Clang 16"
          sudo rm -f /usr/bin/clang++
          sudo ln -s /usr/bin/clang++-16 /usr/bin/clang++

          # Display the installation directory and version of the installed Clang
          echo "-----> Clang-16 was installed on:"
          which clang-16
          echo "-----> Clang++ was installed on:"
          which clang++-16

      - name: Generate a Zork++ release build
        run: |
          cd ./Zork/zork++
          cargo build --release
          cd ../..
          mv ./Zork/zork++/target/release/zork ./Zork/zork++/target/release/zork++
          cp ./Zork/zork++/target/release/zork++ .

      - name: Running the tests for ${{ matrix.os }} with Zork++
        run: ./zork++ --match-files gh_linux -vv test
